name: Get Node versions
on:
  push:
    branches: [ test-ubuntu-24.04 ]

jobs:
  get-new-node-versions:
    uses: aparnajyothi-y/versions-package-tools/.github/workflows/get-new-tool-versions.yml@main
    with:
      tool-name: "Node"
      image-url: "https://nodejs.org/static/images/logo-hexagon-card.png"
    secrets: inherit
